# Generated by Django 4.2.7 on 2023-11-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('category', models.CharField(choices=[('J', 'Jardineria'), ('L', 'Limpieza'), ('A', 'Autos'), ('H', 'Hogar'), ('C', 'Comida'), ('O', 'Otros')], default='O', max_length=5, verbose_name='Categoria')),
            ],
        ),
    ]
