# Generated by Django 4.2.7 on 2023-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='sell_detail',
        ),
        migrations.AddField(
            model_name='bill',
            name='selldetail',
            field=models.ManyToManyField(related_name='selldetail', to='bills.selldetail'),
        ),
        migrations.AlterField(
            model_name='selldetail',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
