# Generated by Django 4.2.7 on 2023-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_subtotal_bill_total_alter_bill_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='rtn',
            field=models.IntegerField(blank=True, null=True, verbose_name='RTN'),
        ),
    ]
